services:
    crocos_security.auth_logic.session_entity:
        class: Crocos\SecurityBundle\Security\AuthLogic\SessionEntityAuth
        arguments:
            - @session
            - @doctrine
        tags:
            - { name: crocos_security.auth_logic, alias: session.entity }
