services:
    crocos_security.auth_strategy.facebook:
        class: Crocos\SecurityBundle\Security\AuthStrategy\FacebookAuth
        arguments:
            - @facebook.api
        tags:
            - { name: crocos_security.strategy, alias: facebook }
