services:
    crocos_security.auth_logic.facebook:
        class: Crocos\SecurityBundle\Security\AuthLogic\FacebookAuth
        arguments:
            - @facebook.api
        tags:
            - { name: crocos_security.auth_logic, alias: facebook }
