services:
    crocos_security.context:
        class: Crocos\SecurityBundle\Security\SecurityContext
        calls:
            - [ setPreviousUrlHandler, [ @crocos_security.previous_url_handler ] ]

    crocos_security.checker:
        class: Crocos\SecurityBundle\Security\SecurityChecker
        arguments:
            - @crocos_security.context
            - @crocos_security.annotation_loader
            - @crocos_security.forwarding_controller_matcher

    crocos_security.annotation_loader:
        class: Crocos\SecurityBundle\Security\AnnotationLoader
        arguments:
            - @annotation_reader
            - @crocos_security.auth_strategy_resolver

    crocos_security.forwarding_controller_matcher:
        class: Crocos\SecurityBundle\Security\ForwardingControllerMatcher
        arguments:
            - @controller_name_converter

    crocos_security.previous_url_handler:
        class: Crocos\SecurityBundle\Security\PreviousUrlHandler
        arguments:
            - @session

    crocos_security.auth_strategy_resolver:
        class: Crocos\SecurityBundle\Security\AuthStrategy\AuthStrategyResolver

    crocos_security.auth_strategy.session:
        class: Crocos\SecurityBundle\Security\AuthStrategy\SessionAuth
        arguments:
            - @session
        tags:
            - { name: crocos_security.strategy, alias: session }
